/**
 * Trip Builder — shared StyleSheet for the screen and its leaf components.
 * Extracted verbatim from app/builder/[id].tsx.
 */
import { StyleSheet } from 'react-native';
import { colors, spacing, fontSize, radius, shadow } from '../theme/tokens';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.paper },
  skimBanner: {
    backgroundColor: colors.accSoft,
    borderBottomWidth: 1,
    borderBottomColor: colors.acc,
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.sm,
  },
  skimBannerText: { fontSize: fontSize.sm, color: colors.ink, fontWeight: '600' },
  notFound: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 16 },
  notFoundText: { fontSize: fontSize.lg, color: colors.sub },

  toolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.xl,
    height: 56,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
    flexShrink: 0,
  },
  back: { color: colors.sub, fontSize: fontSize.sm },
  separator: { width: 1, height: 20, backgroundColor: colors.line, marginHorizontal: 4 },
  tripName: { fontSize: fontSize.base, fontWeight: '700', color: colors.ink, flexShrink: 1 },

  budgetChip: {
    paddingHorizontal: spacing.md, paddingVertical: 6, borderRadius: radius.pill,
    backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.line,
  },
  budgetChipOver: { backgroundColor: 'rgba(192,57,43,0.10)', borderColor: '#c0392b' },
  budgetChipText: { fontSize: fontSize.xs, fontWeight: '700', color: colors.ink },
  budgetChipTextOver: { color: '#c0392b' },
  budgetAddChip: {
    paddingHorizontal: spacing.md, paddingVertical: 6, borderRadius: radius.pill,
    borderWidth: 1, borderColor: colors.line, borderStyle: 'dashed',
  },
  budgetAddText: { fontSize: fontSize.xs, fontWeight: '700', color: colors.acc },

  settingsBtn: {
    width: 34, height: 34, borderRadius: radius.pill,
    borderWidth: 1, borderColor: colors.line,
    alignItems: 'center', justifyContent: 'center',
  },
  settingsBtnText: { fontSize: 18, color: colors.ink, fontWeight: '700', lineHeight: 20 },

  emptyHero: { alignItems: 'center', gap: spacing.sm, paddingVertical: spacing.xxl, paddingHorizontal: spacing.lg },
  emptyHeroIcon: { fontSize: 40 },
  emptyHeroTitle: { fontSize: fontSize.lg, fontWeight: '800', color: colors.ink, textAlign: 'center' },
  emptyHeroSub: { fontSize: fontSize.sm, color: colors.sub, textAlign: 'center', maxWidth: 300, marginBottom: spacing.sm },
  emptyHeroBtn: { marginTop: spacing.xs },
  emptyHeroDay: { marginTop: spacing.sm, paddingVertical: spacing.sm },
  emptyHeroDayText: { fontSize: fontSize.sm, color: colors.acc, fontWeight: '600' },

  budgetRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  currencyTag: {
    paddingHorizontal: spacing.md, paddingVertical: spacing.sm,
    borderWidth: 1, borderColor: colors.line, borderRadius: radius.sm, backgroundColor: colors.panel,
  },
  currencyTagText: { fontSize: fontSize.md, color: colors.sub, fontWeight: '600' },

  body: { flex: 1, flexDirection: 'row' },
  phoneBody: { flex: 1 },

  timelineCol: {
    width: 440,
    borderRightWidth: 1,
    borderRightColor: colors.line,
    flexShrink: 0,
    flexDirection: 'column',
  },
  timelineColPhone: { flex: 1 },

  droppable: {
    borderRadius: radius.md,
    marginBottom: spacing.sm,
    borderWidth: 1.5,
    borderColor: 'transparent',
  },
  droppableOver: {
    borderColor: colors.acc,
    backgroundColor: colors.accSoft,
  },
  unassignedHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    padding: spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
  },
  unassignedTitle: { fontSize: fontSize.base, fontWeight: '700', color: colors.ink },
  unassignedSub: { fontSize: fontSize.xs, color: colors.sub },

  dragHandle: { width: 20, alignItems: 'center', justifyContent: 'center', cursor: 'grab' as any },
  dragHandleIcon: { fontSize: 16, color: colors.bar },
  stopRowDragging: { opacity: 0.3 },
  dragOverlay: {
    ...shadow.md,
    borderRadius: radius.md,
    backgroundColor: colors.paper,
    padding: spacing.sm,
  },

  currentDayHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    padding: spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
  },
  dayCircle: { width: 32, height: 32, borderRadius: 16, backgroundColor: colors.acc, alignItems: 'center', justifyContent: 'center' },
  dayNum: { color: colors.white, fontSize: fontSize.sm, fontWeight: '800' },
  dayHeaderInfo: { flex: 1, gap: 2 },
  dayHeaderActions: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  deleteDayBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.paper,
  },
  deleteDayBtnText: { fontSize: fontSize.lg, lineHeight: 22, color: colors.sub, fontWeight: '700' },
  currentDayTitle: { fontSize: fontSize.base, fontWeight: '700', color: colors.ink },
  currentDaySub: { fontSize: fontSize.xs, color: colors.sub },

  stopsContent: { padding: spacing.lg, gap: 0 },
  filterBar: { flexDirection: 'row', paddingBottom: spacing.md },
  logisticsRegion: { gap: spacing.sm, marginBottom: spacing.md },
  logisticsBlock: {
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: radius.md,
    backgroundColor: colors.panel,
    overflow: 'hidden',
  },
  logisticsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
    padding: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
  },
  logisticsTitleWrap: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  logisticsHeaderActions: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  logisticsTitle: { fontSize: fontSize.base, color: colors.ink, fontWeight: '800' },
  logisticsCount: {
    minWidth: 22,
    height: 22,
    paddingHorizontal: 6,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.paper,
    borderWidth: 1,
    borderColor: colors.line,
  },
  logisticsCountText: { fontSize: fontSize.xs, color: colors.sub, fontWeight: '800' },
  inboxBadge: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 3,
    borderRadius: radius.pill,
    backgroundColor: colors.accSoft,
    borderWidth: 1,
    borderColor: colors.acc,
  },
  inboxBadgeText: { fontSize: fontSize.xs, color: colors.acc, fontWeight: '800' },
  logisticsEmpty: { padding: spacing.lg },
  logisticsEmptyText: { fontSize: fontSize.sm, color: colors.sub, textAlign: 'center' },
  logisticsCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    padding: spacing.md,
    backgroundColor: colors.paper,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
  },
  logisticsCardSelected: { backgroundColor: colors.accSoft },
  logisticsMain: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: spacing.md },
  logisticsIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.accSoft,
    borderWidth: 1,
    borderColor: colors.acc,
  },
  logisticsIconText: { fontSize: 18 },
  logisticsSubtotal: { fontSize: fontSize.xs, color: colors.ink, fontWeight: '800' },
  logisticsMeta: { flex: 1, gap: 3 },
  logisticsName: { fontSize: fontSize.sm, color: colors.ink, fontWeight: '800' },
  logisticsDetail: { fontSize: fontSize.xs, color: colors.sub, lineHeight: 16 },
  logisticsCost: { fontSize: fontSize.xs, color: colors.ink, fontWeight: '700' },
  logisticsActions: { alignItems: 'center', gap: spacing.xs },
  emptyHint: { fontSize: fontSize.sm, color: colors.sub, textAlign: 'center', paddingVertical: spacing.lg },

  stopRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, marginBottom: spacing.sm },
  railCol: { width: 16, alignItems: 'center', paddingTop: 14 },
  railDot: { width: 10, height: 10, borderRadius: 5, borderWidth: 2, borderColor: colors.line, backgroundColor: colors.paper },
  railDotActive: { borderColor: colors.acc, backgroundColor: colors.acc },
  railLine: { width: 2, flex: 1, backgroundColor: colors.line, marginTop: 2, minHeight: 16 },

  stopCard: {
    flexDirection: 'row',
    gap: spacing.sm,
    padding: spacing.md,
    backgroundColor: colors.paper,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.line,
  },
  stopCardSelected: { borderColor: colors.acc, backgroundColor: colors.accSoft },
  stopMain: { flexDirection: 'row', gap: spacing.md, flex: 1 },
  stopPhoto: { width: 72, height: 72, backgroundColor: colors.panel, borderRadius: 8, alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  stopIndex: {
    position: 'absolute', top: -6, left: -6,
    minWidth: 22, height: 22, paddingHorizontal: 5, borderRadius: 11,
    backgroundColor: colors.acc, alignItems: 'center', justifyContent: 'center',
    borderWidth: 2, borderColor: colors.paper,
  },
  stopIndexText: { color: colors.white, fontSize: fontSize.xs, fontWeight: '800' },
  stopPhotoLabel: { fontSize: 10, color: colors.sub, fontFamily: 'monospace' },
  stopPhotoImg: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, borderRadius: 8 },
  stopMeta: { flex: 1, gap: 4 },
  stopLocation: { fontSize: fontSize.sm, fontWeight: '700', color: colors.ink },
  stopMetaRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, alignItems: 'center' },
  stopCat: { alignSelf: 'flex-start' },
  stopTime: { alignSelf: 'flex-start' },
  stopCost: { alignSelf: 'flex-start' },
  timeRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  timeSep: { color: colors.sub, fontSize: fontSize.md },
  geoWrap: { position: 'relative' },
  geoHint: { fontSize: fontSize.xs, color: colors.sub, marginTop: 4 },
  geoDropdown: {
    backgroundColor: colors.paper,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: radius.sm,
    marginTop: 4,
    ...shadow.sm,
  },
  geoItem: { paddingHorizontal: spacing.md, paddingVertical: spacing.sm, borderBottomWidth: 1, borderBottomColor: colors.line },
  geoItemTitle: { fontSize: fontSize.sm, color: colors.ink, fontWeight: '600' },
  geoItemSub: { fontSize: fontSize.xs, color: colors.sub, marginTop: 2 },
  stopCaption: { fontSize: fontSize.xs, color: colors.sub, lineHeight: 16 },
  noLoc: { fontSize: fontSize.xs, color: colors.acc },
  shareBreakdown: { borderTopWidth: 1, borderTopColor: colors.line, paddingTop: spacing.sm, gap: 6 },
  shareBreakdownTitle: { fontSize: fontSize.xs, fontWeight: '700', color: colors.sub, textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 2 },
  shareRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  shareLabel: { fontSize: fontSize.sm, color: colors.ink },
  shareAmount: { fontSize: fontSize.sm, color: colors.sub, fontWeight: '600' },
  shareAmountYou: { color: colors.acc },
  settleLabel: { fontSize: fontSize.sm, color: colors.ink, fontWeight: '600' },
  settleAllEven: { fontSize: fontSize.xs, color: colors.sub, fontStyle: 'italic' },
  assigneeRow: { flexDirection: 'row', marginTop: 4 },
  assigneeAvatar: { width: 18, height: 18, borderRadius: 9, backgroundColor: colors.panel, marginRight: -4, borderWidth: 1.5, borderColor: colors.paper },
  assigneeAvatarFallback: { alignItems: 'center' as const, justifyContent: 'center' as const },
  assigneeInitial: { fontSize: 9, fontWeight: '700' as const, color: colors.sub },

  stopActions: { alignItems: 'center', justifyContent: 'center', gap: 6, paddingLeft: 4 },
  editIcon: { fontSize: fontSize.sm, color: colors.sub },
  reorderIcon: { fontSize: 12, color: colors.sub },
  reorderDisabled: { color: colors.line },
  removeBtnText: { fontSize: fontSize.sm, color: colors.sub },

  addDayBtn: {
    height: 44,
    borderWidth: 1.5,
    borderColor: colors.acc,
    borderStyle: 'dashed',
    borderRadius: radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: spacing.sm,
    marginHorizontal: spacing.lg,
    marginBottom: spacing.lg,
  },
  addDayBtnText: { fontSize: fontSize.sm, color: colors.acc, fontWeight: '700' },

  addZone: {
    height: 52,
    borderWidth: 1.5,
    borderColor: colors.line,
    borderStyle: 'dashed',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: spacing.sm,
  },
  addZoneText: { fontSize: fontSize.sm, color: colors.acc, fontWeight: '600' },

  modalBackdrop: { flex: 1, backgroundColor: 'rgba(44,42,38,0.5)', alignItems: 'center', justifyContent: 'center', padding: spacing.xl },
  modalSheet: { width: '100%', maxWidth: 440, backgroundColor: colors.paper, borderRadius: radius.md, padding: spacing.xl, gap: spacing.sm },
  backpackContent: { gap: spacing.lg, paddingBottom: spacing.sm },
  backpackSection: { gap: spacing.sm },
  backpackSectionTitle: { fontSize: fontSize.sm, color: colors.sub, fontWeight: '900', textTransform: 'uppercase' },
  backpackEmpty: { fontSize: fontSize.sm, color: colors.sub, textAlign: 'center', paddingVertical: spacing.lg },
  backpackCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: radius.sm,
    backgroundColor: colors.panel,
  },
  backpackPhoto: {
    width: 72,
    height: 64,
    flexShrink: 0,
    overflow: 'hidden',
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.paper,
  },
  backpackPhotoImg: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0 },
  backpackPhotoLabel: { fontSize: fontSize.xs, color: colors.sub, fontFamily: 'monospace' },
  backpackBookingIcon: {
    width: 58,
    height: 58,
    flexShrink: 0,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.paper,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backpackFlightIcon: { borderStyle: 'dashed' },
  backpackBookingIconText: { fontSize: fontSize.xs, color: colors.acc, fontWeight: '900', textTransform: 'uppercase' },
  backpackCardMain: { flex: 1, minWidth: 0, gap: 4 },
  backpackName: { fontSize: fontSize.sm, color: colors.ink, fontWeight: '800' },
  backpackMeta: { fontSize: fontSize.xs, color: colors.sub, lineHeight: 16 },
  backpackCopy: { fontSize: fontSize.xs, color: colors.ink, lineHeight: 16 },
  modalTitle: { fontSize: fontSize.lg, fontWeight: '700', color: colors.ink, marginBottom: spacing.xs },
  locStatus: { backgroundColor: colors.panel, borderRadius: radius.sm, paddingHorizontal: spacing.md, paddingVertical: spacing.sm },
  locStatusText: { fontSize: fontSize.sm, color: colors.ink },
  modalLabel: { fontSize: fontSize.sm, color: colors.sub, marginTop: spacing.sm },
  input: {
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: radius.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    fontSize: fontSize.md,
    color: colors.ink,
    backgroundColor: colors.panel,
  },
  inputMultiline: { minHeight: 60, textAlignVertical: 'top' },
  catRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  modalActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: spacing.md, marginTop: spacing.lg },

  mapCol: { flex: 1 },
  routeInfo: {
    position: 'absolute',
    left: 16,
    top: 16,
    backgroundColor: colors.paper,
    padding: spacing.md,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.line,
    gap: 4,
    ...shadow.sm,
  },
  routeInfoTitle: { fontSize: fontSize.md, fontWeight: '700', color: colors.ink },
  routeInfoSub: { fontSize: fontSize.xs, color: colors.sub },
  sidePanel: {
    position: 'absolute',
    right: 16,
    top: 16,
    bottom: 16,
    width: 390,
    maxWidth: '48%',
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.paper,
    overflow: 'hidden',
    ...shadow.md,
  },
  sidePanelPhone: {
    left: 12,
    right: 12,
    top: 12,
    bottom: 12,
    width: undefined,
    maxWidth: '100%',
  },
  sideTabStrip: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 2,
    minHeight: 42,
    paddingHorizontal: spacing.sm,
    paddingTop: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
    backgroundColor: colors.panel,
  },
  sideTab: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    maxWidth: 168,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderTopLeftRadius: radius.sm,
    borderTopRightRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.bar,
    marginBottom: -1,
  },
  sideTabActive: {
    backgroundColor: colors.paper,
    borderBottomColor: colors.paper,
  },
  sideTabText: { flex: 1, minWidth: 0, fontSize: fontSize.xs, color: colors.sub, fontWeight: '900' },
  sideTabTextActive: { color: colors.ink },
  sideTabClose: {
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sideTabCloseText: { fontSize: fontSize.xs, color: colors.sub, fontWeight: '900', lineHeight: 14 },
  sidePanelBody: { flex: 1, padding: spacing.md, gap: spacing.sm },
  sidePanelHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.md },
  stayPanelTitleWrap: { flex: 1, minWidth: 0 },
  stayPanelTitle: { fontSize: fontSize.lg, color: colors.ink, fontWeight: '800' },
  stayPanelSub: { fontSize: fontSize.xs, color: colors.sub, marginTop: 2 },
  stayFilters: { gap: spacing.sm },
  stayFilterRow: { flexDirection: 'row', alignItems: 'flex-end', gap: spacing.sm },
  stayField: { flex: 1, minWidth: 0, gap: 4 },
  stayFieldSmall: { width: 74, gap: 4 },
  stayLabel: { fontSize: fontSize.xs, color: colors.sub, fontWeight: '800', textTransform: 'uppercase' },
  stayInput: {
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: radius.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    fontSize: fontSize.sm,
    color: colors.ink,
    backgroundColor: colors.panel,
  },
  staySortRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs },
  staySortChip: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: radius.pill,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.panel,
  },
  staySortChipActive: { backgroundColor: colors.acc, borderColor: colors.acc },
  staySortText: { fontSize: fontSize.xs, color: colors.sub, fontWeight: '800' },
  staySortTextActive: { color: colors.white },
  stayList: { gap: spacing.sm, paddingBottom: spacing.sm },
  stayLoading: { paddingVertical: spacing.xl },
  stayEmpty: { fontSize: fontSize.sm, color: colors.sub, textAlign: 'center', lineHeight: 20, paddingVertical: spacing.lg },
  stayNotice: { gap: spacing.xs, paddingVertical: spacing.md },
  stayNoticeTitle: { fontSize: fontSize.base, color: colors.ink, fontWeight: '800' },
  stayNoticeText: { fontSize: fontSize.sm, color: colors.sub, lineHeight: 20 },
  stayCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: radius.sm,
    backgroundColor: colors.panel,
  },
  stayCardActive: { borderColor: colors.acc, backgroundColor: colors.accSoft },
  stayCardMain: { flex: 1, minWidth: 0, gap: 5 },
  stayCardTop: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  stayName: { flex: 1, minWidth: 0, fontSize: fontSize.sm, color: colors.ink, fontWeight: '800' },
  stayScore: { fontSize: fontSize.sm, color: colors.acc, fontWeight: '900' },
  stayWhy: { fontSize: fontSize.xs, color: colors.sub, lineHeight: 16 },
  stayMetaRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 5 },
});

